# Permalinks
permalink:        pretty

# Setup
title:            dfa.io
tagline:          a regular tech blog
url:              http://dfa.io
paginate:         1
baseurl:          /
gems: [jekyll-paginate]
author:
  name:           Evan Bergeron
  url:            https://dfa.io
  email:          ebergeron@cmu.edu

pages_list:
  About: '/about'
  # Archive: '/archive'

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/dfaio/dfaio.github.io
