#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="no.css" />
#+OPTIONS: toc:nil
#+OPTIONS: num:nil
#+OPTIONS: html-postamble:nil
[[file:index.html][dfa.io]]
* 2021
** Jan 23 - Darth Bane trilogy first book
  
This book has spoilers for the KOTOR game series, so if you haven't
played those and still intend to, start there. (I still haven't played
them myself and was a bit bummed to hear how some of the storylines
played out).

The book is pretty good. Easy to read. The writing style is breezy. I
could have done without the romantic subplot. Bane's origin story is
believable and well done. The book overall doesn't have a lot of
description - many character's physical appearance is maybe briefly
mentioned. The same is true for physical locations.

I don't know how well the ending sets up the rest of the series. I'm
not sure I will continue to read the rest of the trilogy.

I would say this novel is not as good as the Thrawn trilogy, but is
still an enjoyable story. I like the Old Republic setting (largely
because it avoids any mention of the Skywalker saga). I recommend this
book to anyone looking for an easy-to-read Sith-centered origin story.

** Jan 30 - Parable of Sower
Frankly depicts many serious themes. Real page turner. Protagonist is
likeable and relatable. I started reading this a while back and only
got 40 pages in. It picks up after that point. Lots of interesting
tropes in this book as well, though I'll refrain from talking about
them here for fear of spoilers.
  
* < 2021

** Coders, the Making of a New Tribe.

A book on programmer culture over the years. The author knows how to code some, but is not a programmer by trade. There's discussion programmer mental health, gender inequality, and social norms. The chapter 'The ENIAC girls' taught me that programming was originally a largely female profession. There is discussion of the bootcamp phenomenon.

The book made me think about the culture of the industry I work in. I
recommended it.

** More Happy Than Not

A queer love story with a surrealist twist. The first queer fiction
I've sought out.

** Goodbye, Things

One of my favorite books on minimalism. The author is open about his
insecurities and the ways in which he would use things to compensate:
abstruse books to seem literary, a big TV to seem like a film
enthusiast.

