#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="no.css" />
#+OPTIONS: num:nil
#+OPTIONS: html-postamble:nil
[[file:index.html][dfa.io]]
Some nice things to cook and eat. Some of these things I've made many
times, some of this is a wishlist reference for myself.
* Fried rice
Couple of details I like:

- Let the rice sit on the pan for a while so it gets real crispy.
- Fry the egg whites separately from the yolk for varied texture and color.
  
Couple different flavor profiles:

- Fish sauce (tablespoon per block of tofu), light rice vinegar,
  cilantro, mint, jalapenos (and fermented jalapeno sauce), crab,
  kumquats.
- Soy sauce, dark rice vinegar, shaoxing rice wine, chili oil, five
  spice sasuage.
  
I usually just fry up a block of tofu and stick it in with the veggies.

Tips to prep before:

- Chooped boy choy and carrots keep nicely in the fridge.

Haven't found a tofu marinade I like much. It seems to make it wetter,
which prevents it from getting crispy in the frier. 

* Sandwich bread
Joy of Cooking white bread toasts up well nicely on a cast iron pan.

A bit of buckwheat flour can be quite good, as well. I've settled on
about a 1:4 ratio buckwheat to non-buckwheat.

* Cinnamon-garlic-ginger garbonzo bean soup
From the Everything I Want to Eat cookbook. Easy and
delicious. Cinnamon in beans is good.

* Slow cooked pork
Cut pork shoulder into about 3x3x3 inch blocks. Place in slow cooker
with a half cup water and a half teaspoon salt for each pound of
meat. Cook on low for 8 hours. Fries up nicely.

Keeps in the fridge for a couple days, I didn't get sick eating it 3
days later (having cooked it on the sell-by date).

Good on whatever. Burritos, fried rice.j

* Burritos, arepas, tacos
Rice, beans, chorizo, carnitas, eggs, cheese (I like feta on
everything), cilantro, salsa, hot sauce.
* Coconut milk lentil curry
Add the coconut milk at the end. Fry the whole spice masala in oil at
first, use that oil to fry the onions, garlic, etc. Then pour in beans
and water, wait a while, pour in coconut milk, and enjoy.

Nice with sweet potatoes, squash, maybe some roasted cauliflower.

* Mapo tofu
Pixian doubanjiang is the critical ingredient. I've only tried the
Juan Cheng brand. I'm no expert on the topic, I asked a friend for a
recommendation. It's a fermented bean paste.

Cube tofu and soak in salt water for about 15 mins while frying onion,
garlic, then add ground pork and doubanjiang. Add a bit of sugar, some
five spice powder, and some cornstarch and water.

Add tofu cubes on top, cook for 15 mins or so. Serve over rice or
whatnot.

* Italian sasuage sweet potato kale soup
One package italian sasuage, a big sweet potato, bunch of kale (or
spinach or chard), one quart chicken broth. Put it in a pot, cook, enjoy.

* Tomatillo bean soup
The pozole recipe from Everything I Want To Eat. Delicious. Don't know
how much work it is, I've never made it personally :P

* Empanadas
[[https://www.laylita.com/recipes/beef-empanadas/][Apparently a good reference]]. Try with dried fruit (apricot), almond,
walnut, chimichurri. I've never made these, this is the wishlist part
of the cookbook :P

* Sauces
** Lacto-fermented hot sauces
I like it best with jalapenos and serranos. Tried it with poblanos and
didn't like it much. Haven't tried with haberanos yet. A good friend
of mine made a delicious fermented haberano sauce with honey.

Stem and seed about a pount of peppers. Puree. Add salt (0.075 x the
weight of pepper puree). Stir. Place in big mason jar, wait 4 weeks.

Be sure the peppers are totally covered by the brine. Feel free to add
more brine if needed (not sure how the added brine strategy plays out,
that's still a WIP).

At the end of the 4 weeks, place the pepper puree in some vinegar
(TODO how much?) and briefly boil. Keeps in the fridge for about 6
months, apparently.

** Chili Oil
Still new to me, on my second try.

- Canola Oil (obv not ideal)
- Chinese dried peppers (not sure on the details)
- Sichuan peppercorns, toasted and ground
- Anise, toasted and ground.
  
Some tweaks and things to try:

- Use a peanut oil of Chinese manufacture.
- Experiment with different dried peppers
- This second time I tried soaking the peppers in water after
  toasting, as if I was making mole. I also chopped the peppers into
  small rings.
- More "five spices" - fennel, cloves, and (cassia?) cinnamon.
- Fried soybeans

** Salsas
Our fave is wrapping garlic, tomatillos, and serranos in some foil and
heating in a pan for maybe 20-30 mins, then puree-ing with some salt
and lime. Mmmm serranos.
