#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="no.css" />
#+OPTIONS: num:nil
#+OPTIONS: html-postamble:nil
[[file:index.html][dfa.io]]

* Mwi is a small town.

No more than a dozen wood buildings centered around a single road in
and out of town, running east-to-west. You notice a number sunbleached
wagons stationed surrounding the building.

Sheriff Horace Moorhead asks for the marked to travel to the
canyons. He has a goatee. Word from the east has rumour of a red
crystal that burns blue.

The booms in the great canyons to the west have been bothering the
townfolk as well.

- A butcher named Ori (raw meats hanging)
- A seamstress (has great deal of sturdy tan and brown fabric,
  including has some checked fabric, large checks perhaps the width of
  ones hand. Deep brown and deep navy.
- A bar named The Clayhorn Saloon. The bartender mentions the crystals
  allegedly bring eternal life. The bar has cactus liquor.

First settled 15 years ago. Most came from the south, driven by poverty
and a promise of a better life.
  
Players stole a canteen from the saloon. Willow got checked bootie
shorts. Silvana wraps checked scarf around her face. Smoked some
mugwort with the bartender. Harassed by Twitch, the local
drunk. Twitch called the party "Windburns". There was a child in the
streets with a necklace of bones.

The sheriff wants the crystal. Ashes followed Scrib. 

* Into the canyon

Willow had a vision of a shatted tree. Two great booms from the
canyon. Took steps down into the canyon. There's a river at the bottom
of the canyon. Acidic smelly caves. A fight with a giant
worm. Everyone ate the worm. Willow got a corset made from the worm
teeth.

Some sediment from the smelly cave. Bees
in a giant ribcage, ashes got a bit of the honey. The crystalline
door. Ashes puked, slightly stung by the bees, smoked mugwort to help

They find a plant that gives them this dream:

"Stare at the horizons. Opposite each other, they meet at a single
point. Blue flame, a bent crystalline sphere. Spiders have many eyes."

Then, a a 6-pointed web appears stretched over a circle. A 7th point
is born. An 8th, then a 9th.

* Behind the door

- Yellow cavern
- Vats of red crystal and red crystal powder that burn with blue flame.
- White crystalline salt on the ceiling that burns with purple flame.
  
Meet an undead monk who claims his people were run out. Giant undead
worm appears. It's split into two animated portions. The monk says his
people looked for eternal life via the crystals, but says the crystal
bring only death and cold.

Delshay arrives, a similarly marked traveler who arrives from
Mwi. Folks takes some of the crystals. Willow takes the undead monk's
weapon - a melee-range shotgun of sorts, that you load with the powder
and set off.

The door to the cave closed up after going back outside.

* Back to Mwi

A merchant named Aapo is in town. He brings a captured slave to the
south. The slave is wanted to the north. Aapo buys some crystal from
the players for 12 gold in front of the sheriff. Players don't give
anything to the sheriff. Ashes seems to convince Moorhead that they've
achieved immortality from the crystals.

Scrib is jailed (as we later find out, for sleeping with the wife of
the sheriff of the town over).

Meet Jacobi, a man living on the outskirts of Mwi. He sells golden
shovels to "shovel yourself out of the shit." He trades some "honey of
the night" for the red crystal that burns blue.

Players bust Scrib out of jail, blowing up the jail cell in the process.

* The pumice plains

A fight with a pumice golem that is drawn to fire. Health: 25,
Intellect defense as level 2, Speed defense as level 3, Armor 4, giant
hammer that deals 8 damage.

* Toadrind makes Maeha soup.
  
Toadrind lives out between Mwi and Scornsnag. He hunts and eats
Taceeenee - he has a spoon made of their horns, has a bow string made
of the ankle sinew (tendons), fat from the tallow. He makes soap from
the tallow and sells that. First have to make lye (which is done when
an egg floats).

He offers the players a deal to pay them for hunting Maeha and
bringing back their bodies. The players turn down buying a body bag
from him. The players eat a bit of the meat soup before realizing the
Maeha have human-like faces.

Ashes' finger is going numb. 

* Scornsnag is laid to waste.

Some townspeople are nailed to wooden spikes in the ground by their
necks. There is a church in the middle of town. The players wait
outside the town overnight in watch, but nothing happens. When they
enter the town the next day, they are set upon by carrion birds. They
kill the carrion birds and bury the dead.

* Robinya rides a sandsail.

She has red cactus flowers on top of her head. She has an eye patch
over here right eye. Two axes with horn handles. She rides a sandsail,
a giant one wheel vehicle made of wood with a tan sail and a side
car. Four henchman ride with her.

She works for Aapo and attempts to fight the players, though they
handily defeat her. The players offer to trade crystals for the
sandsail, but she refuses after some hesitation and rides off, saying
"I can guaran-goddamn-tee this ain't the last you'll see of me!"

* Crossing the river
  
Water snakes bask on the algae-covered rocks. Will bite, poop, and
release musk (smells like dead fish) if picked up. The smell
lingers. The snakes are 2 to 4 feet long, brown, gray, reddish, or
brownish-black.

They have crossbands on the neck and dark blotches on the rest of the
body. They have flattened head the same width as the neck, round
pupils, and heat-sensing pits.

* Meeting Calian
  
A young Maeha man. Sharp nose, long braided hair. The front of his
hair tied together in a sort-of horn almost. There's braids behinds
both of his ears. The back of his neck has shorter, thicker hair.

Has horns above and behind his ears, wears his braids tucked over his
horns. Horns are short, fairly vertical, curve up and out. Simple
wooden pipe. Septum piercing. Gathering blue flax. Light blue flower
pedals. The seeds sooth the stomach. Makes strong rope.

Ashes offers him meat, but he says he's vegan. Calian Leads the
players to the edge of his people's village. Says the marks on the
players faces remind him of a legend of his people. Says his mother
will know more.

* Battle at the earthen home

A great mosaic across one of the wall. The home is surrounded by a
food forest. The players make a trap at the entrance of the door to
trap the skeleton monk has he arrives.

When he does, he calls to Ashes to join him, to "become the
thirteenth."

Willow convinces the skelly monk to enter the home, tricking him into
falling into the hole laid with explosives. A swarms of bees rises
from the smoke.

* Clayhorn bowls
  
Having proved their might to the Maeha chieftess, she now says says
their people speak of a great ancient Maeha named Calian (the namesake
of the Calian the players meet). Calian the Great also beared a mark
on his face like the players'. He communed with his ancestors in a
pilgrammage across the land. To set off on his journey, he drank of a
stew to induce a vision.

To commune with their ancestors, the players must craft a bowl made of
clay from the body of a clayhorn.

The players find and fight a clayhorn. Scrib is inside the clayhorn
for most of the battle, somewhat helpless. They drag most of the body
to the river and take back enough to make their bowls.

Ashes makes a bowl that resembles a hand.

The ritual commences.

* Silvana sees sideways mountains, fire and fruit.

Her vision begins as she wanders around as a child, gathering sticks
to toss in the hot fire. She places the stick on the edge and singes
her fingers.

She wanders into the woods. Some time passes, and she lost amongst the
trees in the starlight. Most of the birds are asleep. No one notices
she's gone for some time.

Dyani arrives, brings her back to the fire. They sit together staring
at the fire and she loses herself in the fire.

Suddenly, Silvana finds herself beneath a great tree.

* Into the Mtho high plains
  
A bird of ash fly overhead on the staircase up to the plains. Fight
donkeys. Ashes rode one of the donkeys after Willow tamed it (it's
cognizant). Yak-driving, stone-throwing caravan of wool
trading. Glacier to the northwest in front. Fight spotted cat two
legged creatures.
* Sonam, Dolma, and the Gartok outpost
We met Dolma and Sonam. Ate food with them, they said dont tell that
we're eating meat. Nettle spinach tea, rancid butter tea, meat soup.

Gartok outpost. Paper with a plan for a bomb. Traded three crystals
for the recipe - 2 parts red crystal, 1 part yellow crystal, 1 part
Shaam milk, put it in a coconut.

Bought 7-sided crystal sphere thing from a bald man with a chunk out
of his ear.

Everyone got a tattoo'd pig foot, Silvana got a tattoo of an eye on
her left hand.

Silvana got stoned with Willow.
