#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="sans.css" />
#+OPTIONS: num:nil
#+OPTIONS: html-postamble:nil

This system is heavily based off the Cypher System by Monte Carlo
games. If these rules sound interesting, I encourage you to go buy
their book!

* Players have might, speed, and intellect points.
These are combined health / mana pools. Physical damage reduces your
might pool, some magical damage can reduce speed or intellect. Most
spells require spending intellect points. Many specialized physical
attacks require spending might or speed.

You can spend pool points to add any roll. At first level, you can
spend up to 3 pool points to add 3 to a single roll. This called using
*effort*.

Each of your pools has an associated *edge*. Edge reduces the cost of
*effort*. An edge of 1 decreases the cost of *effort* by one, an edge
of 2 decreases by 2, and so on.

You are an adjective noun that verbs.

* Choose a noun
** Fighter
- Might 10, Edge 1
- Speed 10, Edge 0
- Intellect 8, Edge 0

And an additional 6 points to distribute as you choose.

You are practiced in all weapons and can use them without penalty.

*Choose* three special abilities:

- *Come and get me*.  Spend 1 int. Roll to convince creature to
  physically attack you next round. They snap out of it at the end of
  their turn. Gets more difficult by one step each attempt.
- *Quick on the draw*. You get +3 to your initiative rolls.
- *Shove*. Spend 1 might to melee attack and move an opponent into a
  position you desire within immediate range. Deals 1 less damage than
  usual.
- *Stab*. Spend 1 might to deal 1 extra damage with a weapon with a sharp point.
- *Daze*. Spend 1 might point to daze an opponent for one round,
  during which time the difficulty of all their actions is increased
  by 3. Deals one less damage than usual.
- *Sharpshooter*. Spend 1 speed to deal 1 extra damage with a ranged
  weapon.
- *Overwatch*. You use a ranged weapon to target a narrow location
  (e.g. a hallway or just above a rock etc.) and attack the first
  creature that appears. This is a trigger action (occurs when someone
  appears). This attack negates any advantage the creature would have
  from cover or surprise (+3 and +6 to difficulty, respectively).
** Traveler
- Might 10, Edge 1
- Speed 9, Edge 0
- Intellect 9, Edge 0

And an additional 6 points to distribute as you choose. If you wield a heavy
weapon, increase the attack difficulty by 3.

*Choose* three special abilities:

- *Danger sense*. The difficulty of your initiative is reduced by 3.
- *Block*. Spend 3 speed points to automatically block the next melee attack against you.
- *Decipher*. Spend 1 intellect point to examine a piece of writing or code you
  do not understand. Make a intellect roll of 3 (or higher, depending on the
  code or language). On success, you get the gist of the message. If used
  in combat, takes an action.
- *Endurance*. Any duration of physical action is halved or doubled. E.g. you can
  march twice as long in a day, or poison wears off twice as fast, or you can
  hold your breathe twice as long. Minimum duration one round.
- *Fleet of foot*. If you succeed a difficulty 6 speed roll to run, you can move
  a short distance and take an action in the same round.
- *Strive*. Spend 2 might points to reduce the difficulty of all non-attack might-based
  rolls by 3. Lasts 10 minutes.
- *Special short*. Reduce damage by 1. Instead, hit in a precise spot
  and e.g. shoot an object out of the creature's hand, unbuckle a bag,
  shoot leg or limb to reduce speed to immediate distance for a few
  days (or until receives medical care).
- You have a Might Edge of 1 and a Speed Edge of 1.
- You are trained in two skills you are not already trained in.
- You can use heavy weapons.
** Seer
- Might 7, Edge 0
- Speed 9, Edge 0
- Intellect 12, Edge 1

*Choose* three special abilities:

- *Truesight vision*. You carry with you a plant offering temporary
  truesight vision. Upon smoking, the plant offers you insight into
  nature of the world around you. This can be the level of a creature,
  or the fact that there is a metal object in a nearby wooden chest,
  etc. After a few moments, the truesight ends and you are left
  mentally befuddled. Costs 2 intellect points.
- *Warding*. You once happened across a plant of warding. You gain 1 Armor
  permanently.
- *Mindkiller*. Spend 1 intellect to deal either 2 intellect damage or 4 physical damage. The
  intellect damage
  action next turn. Agreed upon by the GM prior to rolling.
- *Mind trick*. Spend 1 intellect to convince cognizant creature to do
  a reasonable action next turn. Agreed upon by the GM prior to
  rolling.
- *These are not the droids you're looking for*. Spend 1 intellect
  point to convince an individual that you are not part of a group of
  people. For instance, you are not from a certain town or tribe. The
  effect lasts for 1 hour or until the individual learns of facts
  otherwise. To cast on multiple creatures, 1 additional intellect
  point per creature.
- You are *trained* in intellect defense tasks and have +2 to armor against
  damage that selectively targets intellect (this normally would rely on your
  usual armor).

** Rogue
- Might 10, Edge 1
- Speed 9, Edge 0
- Intellect 9, Edge 0

And an additional 6 points to distribute as you choose. If you wield a heavy
weapon, increase the attack difficulty by three.

*Choose* three special abilities:

- *Danger sense*. The difficulty of your initiative is reduced by 3.
- *Block*. Spend 3 speed points to automatically block the next melee attack against you.
- *Decipher*. Spend 1 intellect point to examine a piece of writing or code you
  do not understand. Make a intellect roll of 3 (or higher, depending on the
  code or language). On success, you get the gist of the message. If used
  in combat, takes an action.
- *Endurance*. Any duration of physical action is halved or doubled. E.g. you can
  march twice as long in a day, or poison wears off twice as fast, or you can
  hold your breathe twice as long. Minimum duration one round.
- You have a Might Edge of 1 and a Speed Edge of 1.
- *Fleet of foot*. If you succeed a difficulty 6 speed roll to run, you can move
  a short distance and take an action in the same round.
- *Goad*. After you successfully attack a creature, the difficulty of
  all others speed defense against the creature's attacks decreased by
  three until the next round.
- *Nightstrike*. When you attack in dim light or darkness, you get a
  free level of effort on the attack.
- *Sleight of hand*. 1 speed point. You can e.g. move a object from
  your hand to a desired spot (e.g. your pocket). You can make someone
  believe they have something in their possession that they do not
  have (or vice versa). You can switch objects right in front of
  someone's eyes. Action.
- *Opportunist*. You have an asset on any attack roll you make on a
  creature that has already been attacked this round and is within immediate range.
- You are trained in two skills you are not already trained in.

* Choose an adjective
** Charming
+2 Intellect. *Trained* in pleasant social interaction and special
abilities that influence the minds of others. You not much of a
bookworm and so *struggle* in lore, knowledge, or understanding and
resisting mental attacks.

** Driven
+2 Might. Trained in intellect defense. Each day you are *trained* in
a skill of your choice that you believe will help you reach your
goal. You are so focused on your mission, you don't notice other
things and *struggle* on all perception tasks.

When you choose this descriptor, choose a mission you want to
accomplish. You probably talk about it a lot. When you accomplish the
mission, choose another.

** Exiled
+2 might. As a loner, you gain no benefit when someone with training
helps you with a task. You're *trained* in sneaking, foraging,
hunting, and finding safe places. Your extended solitary time causes
you to *struggle* in social situation.

Perhaps you committed a horrible deed or carry some token from an
earlier, cheerier time in your life.

** Intelligent
+2 intellect. *Trained* in area of knowledge of your choice and all
tasks that draw from your memory.
  
** Maeha
+2 might. You are half human, half bison. You are *trained* in
foraging, nature-based history, smell-based perception checks, and a
sense of direction in the open plains. You *struggle* with
vision-based perception checks. Your permanent horns are a medium
weapon.

** Mysterious
Trained in stealth and resisting interrogation. Once per recovery
period, you can attempt any action as if you were trained in it. You
*struggle* in getting people to believe or trust you.

** Perceptive
+2 intellect. *Trained* in finding or noticing small
details, identifying objects, recalling trivia, and intimidating
another creature. You *struggle* in positive social interaction.

** Rugged
*Trained* in climbing, jumping, running, swimming. *Trained* in
training, riding, or placating natural animals. Trained in
identifying or using natural plants. You struggle with charm,
persuasion, etiquette and deception.

** Sharp
Trained in initiative and perception. If an opponent has a
straightforward weakness, the GM will tell you.

** Spiritual
+2 intellect. Trained in pleasant social interaction,
intellect defense tasks, and resisting temptation. When you help
someone, they add 1 to their roll. You hesistate when taking in
novel details, and so *struggle* with initiative actions.

** Stealthy
+2 speed. Trained in stealth, lying, and trickery and all such special
abilities. You're stealthy but not fast and so struggle with
movement-related tasks.

* Choose a verb
** Abides in pumice
You are a creature of pumice, not flesh. You can move, speak, and feel
pain. Your pumice body makes it harder to take damage, but also harder
to heal. You typically do not wear clothes, though your stone frame
may be carved as such.

Minor effect suggestion: you step on the target and prevent it from
moving next turn.  Major effect suggestion: you break a weapon,
shield, or piece of armor the target is using.

You gain +1 to armor, +1 might edge, and 5 additional might
points. You do not need to eat or drink or breathe (though you still
need to rest and sleep). You move more stiffly than a creature of
flesh, so can never be trained in speed defense rolls. You are
practiced as using your stone fists as a medium weapon.

You are unable to use the first, single-action recovery roll of the
day. Thus, the first recovery roll uses ten minutes, the second uses
an hour, and the last requires ten hours.
** Carries a quiver
Minor effect suggestion: hit in a tendon or muscle, the target takes 2
points of speed damage as well as normal damage. Major effect
suggestion: the target is pinned in place with an arrow.

You can spend points from either speed or intellect when applying
levels of effort to increase bow damage.
** Fights dirty
Minor effect suggestion: You make the foe trip and fall prone. Major
effect suggestion: You tangle something around you foe's leg and they
lose their next turn.

When your foe is disadvantaged in any way, the difficulty of attack is
decreased by three.

You are trained in deception.
** Heals
Minor effect suggestion: the target is healed for 1 extra point. Major
effect suggestion: the target is healed for 2 extra points.

1 intellect point. With a touch, you restore 1d6 points to any stat
pool of a creature. Difficulty 6 intellect task. Each time you use
this on a creature, the difficulty increases by three. Difficulty
returns to 6 after the creature takes a long rest.
** Hunts with great skill
Minor effect suggestion: You can attempt an intimidating task to cause
your foe to immediately surrender.  Major effect suggestion: Your foe
pauses, terrified, and takes no action on their turn.

You are trained in following and identifying tracks. You are trained
in all types of movement (climbing, swimming, jumping, balancing).

** Lives in the wilderness
Minor effect suggestion: A natural creature foe flees. Major effect
suggestion: A natural creature foe becomes warily passive.

Trained in climbing, swimming, wilderness navigation, and identifying
plants and creatures.

** Murders
Minor effect suggestion: no one but the foe notices your attack.
Major effect suggestion: if you have poison, you apply it just before
the strike, adding poison's effects to the normal damange.

If you attack with surprise or before an opponent has acted, the
difficulty of your attack is reduced by three. On a successful
surprise attack, you inflict 2 more points of damange.

You are trained in stealth and disguise.
** Wields a fire spear
TODO
** Wields two weapons at once
Minor effect suggestion: Target is intimidated and flees at its next
action. Major effect suggestion: You can make an additional attack
with one of your weapons.

You can wield two light weapons at the same time, making two separate
attacks with a single action. At first level, you can apply effort to
only one of these attacks. Armor applies to both damages.

* Games mechanics
** Players make all the rolls.

Every roll has a difficulty, as determined by the GM. The player must
roll that difficulty or higher to succeed. Rolls typically have bonuses
applied to them.

Some examples of things that reduce difficulty include knowledge of a
situation, quality weapons or armor, training, an advantageous
situation, etc.

Players can spend pool points to lower difficulties.

Rolling a natural 19 or 20 (assuming the roll is a success against the
TD) introduces a *minor* or *major effect*, respectively.

Minor effects could be a particular grace to your action, or in
combat, an extra 3 damage, the opponent knocking the foe back,
distracting the foe, etc..

Major effects could be an extra 4 damage, knocking your foe down,
stunning them, etc. Alternatively, in combat, you may take another
action.

The verb you choose gives you some more minor and major effects.

** Attacking and defending

Attacking an opponent is a roll, defending an attack is a
roll. The difficulty of these rolls is equal to the level of the opponent. For
instance, to hit or defend against a level 2 opponent requires a 6 or higher.

Damage and armor are flat numbers.

- *Light weapons* deal 2 damage and reduce TD by 1, as they're quick and easy to use.
- *Medium weapons* deal 4 damage.
- *Heavy weapons* require two hands and deal 6 damage.

Rolling a 17 deals an extra point of damage.
Rolling high can deal more damage.

- 17 deals 1 additional damage.
- 18 deals 2 additional damage.
- 19 deals 3 additional damage or introduces a minor effect.
- 20 deals 4 additional damage or introduces a major effect.

Armor reduces damage by a flat amount, possibly down to zero.

Roll a 1 is bad as well and may introduce a GM complication. I'm not too
familiar on the rules of GM complications now, so we'll keep it simple and
forgiving for now :)

Distance is either *immediate*, *short* (15-50"), or *long*.

** Players get an action per turn.

Example actions include moving to melee attack an opponent in immediate range,
making a ranged attack, performing a short plant ritual, or moving a short
distance.

** Players have three pools of points.

- Might
- Speed
- Intellect

Each pool has an associated modifier called *edge*.

Damage is dealt against one of these pools. Physical attacks against
might. Perhaps a drug inducing clusminess may deal against speed. Some
mystic may attack against intellect.

** Players spend pool points to reduce difficulties.

** Edge reduces the cost of effort.

When spending pool points as effort, subtract the associated edge
modifier from the number of pool points spent.

** Resting restores 1d6 pool points.

These can be distributed amongst the pools as you wish.

The first rest of the day takes an action (e.g. instead of attacking
in combat). The second rest of the day takes 10 minutes. Third takes
an hour. Fourth is 10 hours. So per day, you can gain 4d6 points back.

** Training situationally reduces difficulty.

Being trained in a skill is a plus three bonus. Being specialized is a
plus 6.
